// <auto-generated />
using System;
using CD_Collection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CD_Collection.Migrations
{
    [DbContext(typeof(CD_CollectionContext))]
    [Migration("20210318164506_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("CD_Collection.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtistName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistName1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfTracks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPlayTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistName1");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("CD_Collection.Models.Artist", b =>
                {
                    b.Property<string>("ArtistName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordCompany")
                        .HasColumnType("TEXT");

                    b.HasKey("ArtistName");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("CD_Collection.Models.Album", b =>
                {
                    b.HasOne("CD_Collection.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistName1");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("CD_Collection.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
